import type {NextPage} from 'next'
import Head from 'next/head'

import {ImGithub, ImLinkedin2, ImInstagram, ImTwitter} from "react-icons/im";

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className="bg-black h-screen w-screen text-white">
                <div className="h-full w-32">
                    <div className="flex flex-col items-center pt-4 relative h-full">
                        <div id="logo" className="text-5xl font-bold text-center h-1/6 pt-5">
                            D.
                        </div>
                        <div id="menu" className="relative h-3/6 flex flex-col">
                             <ul className="flex flex-col uppercase gap-y-24 text-sm font-light">
                                 <li className="-rotate-90 font-bold relative">
                                     <span className="z-20 block">Competences</span>
                                     <span className="z-10 w-10 h-10 rounded-full bg-green-400 absolute -top-1/2 right-1/3"/>
                                 </li>
                                 <li className="-rotate-90">A propos</li>
                                 <li className="-rotate-90">Experience</li>
                                 <li className="-rotate-90">Contact</li>
                             </ul>
                        </div>
                        <div id="socialMedia" className="relative h-2/6 flex flex-col justify-center items-center">
                            <span className="h-20 bg-green-400 w-0.5 -mt-5"/>
                            <ul className="text-green-400 text-2xl flex flex-col space-y-4 my-7">
                                <li>
                                    <ImGithub/>
                                </li>
                                <li>
                                    <ImLinkedin2/>
                                </li>
                                <li>
                                    <ImInstagram/>
                                </li>
                                <li>
                                    <ImTwitter/>
                                </li>
                            </ul>
                            <span className="h-16 bg-green-400 w-0.5 flex justify-center items-center"/>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    )
}

export default Home
